---
title: "tidyverse"
author: "Alex Di Genova"
output: rmarkdown::github_document

date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## tidyverse

```{r tidy}
library(tidyverse)
glimpse(mtcars)
```

## tidyverse

operators and verbs

```{r pressure, echo=FALSE}
iris %>%
  select(Petal.Length, Petal.Width, Species) %>%
  filter(Species %in% c("versicolor", "setosa")) %>%
  group_by(Species) %>%
  summarize(
    AvgPetalLength = mean(Petal.Length),
    AvgPetalWidth = mean(Petal.Width))
```

## explore

```{r ggplot}
glimpse(mpg)
ggplot(mpg) + geom_point(mapping = aes(x = displ, y = hwy))

```

### Facets

```{r ggplot2}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color=manufacturer)) +
  facet_wrap(~ class, nrow = 2)
```

## Dplyr

### Filter

```{r filter}
mpg %>% filter(manufacturer == "audi") %>% head()
```
```{r filter2}
mpg %>% filter(manufacturer %in% c("audi","chevrolet")) %>% arrange(desc(year),manufacturer)
```

### select
select columns by name
```{r}
mpg %>% select(model,manufacturer,cyl)
# Select all columns between model and year (inclusive)
mpg %>% select(model:year)
# Select all columns except those between model and year (inclusive)
mpg %>% select(-(model:year))

mpg %>% select(trans, drv, everything())
```

### mutate

```{r mutate}
mpg %>% mutate(delta=hwy-cty) 
mpg %>% summarise(mean(hwy))
mpg %>% group_by(manufacturer) %>% summarize(m=mean(hwy)) %>% arrange(desc(m))
```

## Import  Data

### readr
```{r readdata}
a=read_csv("../data/worldcitiespop.csv.gz")
glimpse(a)
```

other examples
```{r r2}
read_csv("The first line of metadata
  The second line of metadata
  x,y,z
  1,2,3", skip = 2)

read_csv("# A comment I want to skip
  x,y,z
  1,2,3", comment = "#")

read_csv("1,2,3\n4,5,6", col_names = c("x", "y", "z"))
```

parsing numbers
```{r n}
parse_number("$100")
parse_number("20%")
parse_number("It cost $123.45")
```
parsing dates
```{r fechas}
parse_date("01/02/15", "%m/%d/%y")
parse_date("01/02/15", "%d/%m/%y")
parse_date("01/02/15", "%y/%m/%d")
parse_date("12 Enero 2015", "%d %B %Y", locale = locale("es"))
```

guest type
```{r guest}
guess_parser("2010-10-01")
guess_parser("15:01")
guess_parser(c("TRUE", "FALSE"))
guess_parser(c("1", "5", "9"))
guess_parser(c("12,352,561"))
```

## Tidy data

gathering

```{r tidy1}
table4a  %>% gather(`1999`,`2000`, key="year",value="population")
```

spreading
```{r tidy2}
table2 %>%spread(key=type, value=count)
```